version: "3.7"

services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"   # OTLP endpoint for traces and metrics
      - "55681:55681" # Collector debugging interface
      - "9464:9464"   # Prometheus metrics endpoint
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: >
      --config=/etc/otel-collector-config.yaml

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger Traces

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"  # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml